# Generated by Django 4.2.7 on 2023-11-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
        ),
    ]
